using System;
using System.Collections.Generic;

namespace winAlert.Domain.Models;

/// <summary>
/// Represents an alert received from the network.
/// </summary>
public class Alert
{
    /// <summary>
    /// Unique identifier for the alert.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// The severity level of the alert.
    /// </summary>
    public AlertSeverity Severity { get; init; } = AlertSeverity.Info;

    /// <summary>
    /// The source system that generated the alert.
    /// </summary>
    public string Source { get; init; } = string.Empty;

    /// <summary>
    /// Brief title of the alert.
    /// </summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// Detailed alert message.
    /// </summary>
    public string Message { get; init; } = string.Empty;

    /// <summary>
    /// Timestamp when the alert was generated by the source.
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Additional metadata key-value pairs.
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();

    /// <summary>
    /// Whether this alert requires explicit acknowledgment.
    /// </summary>
    public bool RequireAcknowledgment { get; init; } = true;

    /// <summary>
    /// Seconds after which to auto-close if not acknowledged (0 = never).
    /// </summary>
    public int AutoCloseSeconds { get; init; }

    /// <summary>
    /// Whether the alert has been acknowledged.
    /// </summary>
    public bool IsAcknowledged { get; private set; }

    /// <summary>
    /// Timestamp when the alert was acknowledged.
    /// </summary>
    public DateTime? AcknowledgedAt { get; private set; }

    /// <summary>
    /// Timestamp when the alert was received by the system.
    /// </summary>
    public DateTime ReceivedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Gets the response time in milliseconds from receipt to acknowledgment.
    /// </summary>
    public long? ResponseTimeMs => AcknowledgedAt.HasValue
        ? (long)(AcknowledgedAt.Value - ReceivedAt).TotalMilliseconds
        : null;

    /// <summary>
    /// Gets whether the alert should auto-close based on its settings.
    /// </summary>
    public bool ShouldAutoClose => AutoCloseSeconds > 0 && !RequireAcknowledgment;

    /// <summary>
    /// Acknowledges this alert.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown if alert is already acknowledged.</exception>
    public void Acknowledge()
    {
        if (IsAcknowledged)
            throw new InvalidOperationException("Alert has already been acknowledged.");

        IsAcknowledged = true;
        AcknowledgedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Gets a truncated message for display purposes.
    /// </summary>
    /// <param name="maxLength">Maximum length of the message.</param>
    public string GetTruncatedMessage(int maxLength = 200)
    {
        if (string.IsNullOrEmpty(Message) || Message.Length <= maxLength)
            return Message;

        return Message[..(maxLength - 3)] + "...";
    }

    /// <summary>
    /// Gets a human-readable time since the alert was received.
    /// </summary>
    public string GetDisplayTime()
    {
        var elapsed = DateTime.UtcNow - ReceivedAt;

        return elapsed.TotalSeconds < 60
            ? $"{(int)elapsed.TotalSeconds}s ago"
            : elapsed.TotalMinutes < 60
                ? $"{(int)elapsed.TotalMinutes}m ago"
                : elapsed.TotalHours < 24
                    ? $"{(int)elapsed.TotalHours}h ago"
                    : $"{(int)elapsed.TotalDays}d ago";
    }
}
